using Content.Client.Audio;
using Content.Shared._Stories.SCCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class TTSTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public TTSTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionCheckBox(SCCVars.TTSEnabledClient, TtsEnabledCheckBox);

        Control.AddOptionPercentSlider(
            SCCVars.TTSVolume,
            SliderTtsVolume,
            scale: ContentAudioSystem.TtsMultiplier);

        Control.AddOptionPercentSlider(
            SCCVars.TTSVolumeRadio,
            SliderTtsVolumeRadio,
            scale: ContentAudioSystem.TtsMultiplier);

        Control.Initialize();
    }
}
